name: Build
# Avoid triggering two build on PR
# https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-prerelease:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install and Build 🔧
        run: |
          pnpm i
          pnpm run build
          pnpm run build-storybook

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: vue3-compact-template # The folder the action should deploy.
